### ISSUE TITLE
The license file is missing from the repo.

### ISSUE THREAD

**Issue by KOLANICH** [imachug/ThunderProxy#1]

**Comment by purplesyringa** [comment]
Indeed. I don't particularly care about the license of this particular project. Would MIT suit you?

**Comment by KOLANICH** [comment]
Of course it will, thanks.

**Comment by purplesyringa** [comment]
I have added the license in 4213af7537e44fbb80463565bb92ab44acc3b2ea.

**Comment by KOLANICH** [comment]
Thanks.
